
import { Language, LanguageCode } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl' },
  { code: 'zh', name: 'Mandarin', nativeName: '中文' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย' },
];

const enTranslations = {
  appName: "RecipeNest",
  subtitle: "Your personalized AI culinary assistant.",
  loading: "Processing...",
  error: "Failed to generate recipes.",
  emptyError: "Please enter some ingredients.",
  plan: "Plan",
  shop: "Shop",
  stats: "Stats",
  profile: "Profile",
  book: "Book",
  kitchen: "What's in your kitchen?",
  kitchenSub: "Enter your ingredients, and I'll dream up something delicious.",
  generate: "Generate Recipes",
  start: "Start Cooking",
  back: "Back",
  save: "Save Text",
  reset: "Reset",
  reset_data: "Reset All Data",
  clear_history: "Clear History",
  ingPlaceholder: "e.g. chicken, spinach, garlic...",
  servings: "Servings",
  dietary: "Dietary Preferences",
  allergies: "Any Allergies?",
  allergiesPlaceholder: "e.g. Peanuts, Shellfish...",
  time: "Time",
  mins: "Mins",
  calories: "Calories",
  kcal: "kcal",
  protein: "Protein",
  carbs: "Carbs",
  fat: "Fat",
  ingredients: "Ingredients",
  instructions: "Instructions",
  people: "People",
  protocol: "Today's Protocol",
  insight: "AI Insight",
  mood_mode: "Mood",
  energy_mode: "Energy",
  mood_title: "Serotonin Boost",
  mood_desc: "Prioritizing Omega-3s and Tryptophan for focus.",
  energy_title: "Sustained Energy",
  energy_desc: "Complex carbs and lean proteins for steady fuel.",
  no_plan: "No meals planned yet.",
  create_plan: "Create Plan",
  breakfast: "Breakfast",
  mid_morning_snack: "Mid-morning Snack",
  lunch: "Lunch",
  afternoon_snack: "Afternoon Snack",
  snack: "Snack",
  dinner: "Dinner",
  late_night_snack: "Late-night Snack",
  cat_packages: "Meal Packages",
  sub_veg_package: "Vegetarian Package",
  sub_nonveg_package: "Non-Vegetarian Package",
  sub_mixed_package: "Mixed Combo Package",
  vegetarian: "Vegetarian",
  non_vegetarian: "Non-Vegetarian",
  tag_focus: "Focus",
  tag_fuel: "Brain Fuel",
  tag_endure: "Endurance",
  tag_rest: "Rest",
  cat_beverages: "Beverages",
  cat_sweets: "Sweets & Ice Cream",
  cat_bakery: "Bakery",
  cat_main: "Main Course",
  cat_fastfood: "Fast Food",
  cat_diet: "Healthy & Diet",
  sub_tea: "Tea & Chai",
  sub_coffee: "Coffee",
  sub_cold: "Cold Drinks",
  sub_soft: "Soft Drinks & Juices",
  sub_smoothies: "Smoothies",
  sub_mocktails: "Mocktails",
  sub_laddus: "Indian Sweets (Mithai)",
  sub_halwa: "Halwa",
  sub_barfi: "Barfi",
  sub_syrup: "Syrup Sweets",
  sub_trad: "Traditional",
  sub_cakes: "Cakes",
  sub_pastries: "Pastries",
  sub_cookies: "Cookies",
  sub_pudding: "Puddings",
  sub_icecream: "Ice Cream",
  sub_curry: "Curries",
  sub_rice: "Rice Dishes",
  sub_pasta: "Pasta",
  sub_street: "Street Food",
  sub_salad: "Salads",
  sub_burger: "Burgers & Sandwiches",
  sub_pizza: "Pizza",
  sub_chinese: "Chinese",
  sub_indian: "Indian",
  sub_italian: "Italian",
  sub_mexican: "Mexican",
  sub_keto: "Keto & Low Carb",
  sub_vegan_special: "Vegan Specials",
  sub_sandwiches: "Sandwiches",
  sub_chips: "Chips & Fries",
  sub_high_protein: "High Protein",
  sub_low_carb: "Low Calorie",
  curating: "Curating recipes...",
  no_recipes_book: "Select a category.",
  daily_nutrition: "Daily Nutrition",
  total_intake: "Total Intake",
  no_data: "No data available.",
  recipe_history: "Recipe History",
  favorites: "Favorites",
  language: "Language",
  units: "Units",
  diet_None: "None",
  diet_Vegetarian: "Vegetarian",
  diet_Vegan: "Vegan",
  diet_Keto: "Keto",
  diet_Paleo: "Paleo",
  diet_Gluten_Free: "Gluten Free",
  grocery_list: "Grocery List",
  generate_to_see: "Generate a plan first.",
  items: "items",
  live_cooking: "Live Cooking",
  ing_reference: "Ingredients",
  confirm_reset: "Reset all data? Cannot be undone.",
  confirm_delete_history: "Clear history?",
  copied: "Copied!",
  view_photos: "View Photos",
  generate_more: "Generate More",
  photo_limit: "Max photos reached",
  quota_exceeded: "Daily limit reached. Please try again later.",
  // Personal Diet
  personal_diet: "Personal Diet",
  age: "Age",
  gender: "Gender",
  weight: "Weight",
  height: "Height",
  activity: "Activity Level",
  goal: "Goal",
  male: "Male",
  female: "Female",
  sedentary: "Sedentary",
  light: "Light",
  moderate: "Moderate",
  active: "Active",
  very_active: "Very Active",
  lose_weight: "Lose Weight",
  maintain: "Maintain",
  build_muscle: "Build Muscle",
  target_calories: "Target Calories",
  daily_goal: "Daily Goal"
};

export const TRANSLATIONS: Record<LanguageCode, typeof enTranslations> = {
  en: enTranslations,
  es: {
    ...enTranslations,
    cat_fastfood: "Comida Rápida",
    cat_diet: "Dieta y Salud",
    sub_burger: "Hamburguesas",
    sub_pizza: "Pizza",
    sub_chinese: "Chino",
    sub_indian: "Indio",
    sub_icecream: "Helado",
    sub_cold: "Bebidas Frías",
    sub_sandwiches: "Sándwiches",
    sub_chips: "Patatas Fritas",
    sub_high_protein: "Alta Proteína",
    sub_low_carb: "Baja Caloría",
    view_photos: "Ver Fotos",
    generate_more: "Generar Más",
    photo_limit: "Límite alcanzado",
    quota_exceeded: "Límite diario alcanzado.",
    personal_diet: "Dieta Personal",
    age: "Edad",
    gender: "Género",
    weight: "Peso",
    height: "Altura",
    activity: "Nivel de Actividad",
    goal: "Objetivo",
    male: "Masculino",
    female: "Femenino",
    lose_weight: "Perder Peso",
    maintain: "Mantener",
    build_muscle: "Ganar Músculo",
    target_calories: "Calorías Objetivo",
    daily_goal: "Meta Diaria"
  },
  fr: {
    ...enTranslations,
    cat_fastfood: "Fast Food",
    cat_diet: "Diététique",
    sub_burger: "Burgers",
    sub_pizza: "Pizza",
    sub_chinese: "Chinois",
    sub_indian: "Indien",
    sub_icecream: "Glace",
    sub_cold: "Boissons Froides",
    sub_sandwiches: "Sandwichs",
    sub_chips: "Frites",
    sub_high_protein: "Riche en Protéines",
    sub_low_carb: "Faible Calorie",
    view_photos: "Voir Photos",
    generate_more: "Générer Plus",
    photo_limit: "Limite atteinte",
    quota_exceeded: "Limite quotidienne atteinte.",
    personal_diet: "Régime Personnel",
    age: "Âge",
    gender: "Genre",
    weight: "Poids",
    height: "Taille",
    activity: "Activité",
    goal: "Objectif",
    male: "Homme",
    female: "Femme",
    lose_weight: "Perdre du poids",
    maintain: "Maintenir",
    build_muscle: "Prendre du muscle",
    target_calories: "Cible Calorique",
    daily_goal: "Objectif Quotidien"
  },
  de: {
    ...enTranslations,
    cat_fastfood: "Fast Food",
    cat_diet: "Diät & Gesund",
    sub_burger: "Burger",
    sub_pizza: "Pizza",
    sub_chinese: "Chinesisch",
    sub_indian: "Indisch",
    sub_icecream: "Eis",
    sub_cold: "Kalte Getränke",
    sub_sandwiches: "Sandwiches",
    sub_chips: "Chips & Pommes",
    sub_high_protein: "Proteinreich",
    sub_low_carb: "Kalorienarm",
    view_photos: "Fotos ansehen",
    generate_more: "Mehr generieren",
    photo_limit: "Limit erreicht",
    quota_exceeded: "Tageslimit erreicht.",
    personal_diet: "Persönliche Diät",
    age: "Alter",
    gender: "Geschlecht",
    weight: "Gewicht",
    height: "Größe",
    activity: "Aktivitätslevel",
    goal: "Ziel",
    male: "Männlich",
    female: "Weiblich",
    lose_weight: "Abnehmen",
    maintain: "Halten",
    build_muscle: "Muskelaufbau",
    target_calories: "Zielkalorien",
    daily_goal: "Tagesziel"
  },
  gu: {
    ...enTranslations,
    appName: "RecipeNest",
    subtitle: "તમારો વ્યક્તિગત AI રસોઈ સહાયક.",
    loading: "પ્રક્રિયા ચાલુ છે...",
    error: "રેસીપી બનાવવામાં નિષ્ફળ.",
    emptyError: "કૃપા કરીને સામગ્રી દાખલ કરો.",
    plan: "યોજના",
    shop: "ખરીદી",
    stats: "આંકડા",
    profile: "પ્રોફાઇલ",
    book: "પુસ્તક",
    kitchen: "તમારા રસોડામાં શું છે?",
    kitchenSub: "તમારી સામગ્રી દાખલ કરો, અને હું કંઈક સ્વાદિષ્ટ બનાવીશ.",
    generate: "રેસીપી બનાવો",
    start: "રસોઈ શરૂ કરો",
    back: "પાછા",
    save: "સાચવો",
    reset: "રીસેટ",
    reset_data: "બધો ડેટા રીસેટ કરો",
    clear_history: "ઇતિહાસ સાફ કરો",
    ingPlaceholder: "દા.ત. ચિકન, પાલક, લસણ...",
    servings: "પિરસવાનું",
    dietary: "આહાર પસંદગીઓ",
    allergies: "કોઈ એલર્જી?",
    allergiesPlaceholder: "દા.ત. મગફળી...",
    time: "સમય",
    mins: "મિનિટ",
    calories: "કેલરી",
    kcal: "kcal",
    protein: "પ્રોટીન",
    carbs: "કાર્બોહાઇડ્રેટ",
    fat: "ચરબી",
    ingredients: "સામગ્રી",
    instructions: "સૂચનાઓ",
    people: "લોકો",
    protocol: "આજનો પ્રોટોકોલ",
    insight: "AI સૂઝ",
    mood_mode: "મૂડ",
    energy_mode: "ઊર્જા",
    mood_title: "સેરોટોનિન બુસ્ટ",
    mood_desc: "મૂડ અને એકાગ્રતા માટે ઓમેગા-3.",
    energy_title: "ટકાઉ ઊર્જા",
    energy_desc: "જટિલ કાર્બોહાઇડ્રેટ્સ અને પ્રોટીન.",
    no_plan: "હજુ સુધી કોઈ ભોજન આયોજિત નથી.",
    create_plan: "યોજના બનાવો",
    breakfast: "નાસ્તો",
    lunch: "બપોરનું ભોજન",
    snack: "નાસ્તો",
    dinner: "રાત્રિભોજન",
    tag_focus: "એકાગ્રતા",
    tag_fuel: "બળતણ",
    tag_endure: "સહનશક્તિ",
    tag_rest: "આરામ",
    cat_beverages: "પીણાં",
    cat_sweets: "મીઠાઈ અને આઈસ્ક્રીમ",
    cat_bakery: "બેકરી",
    cat_main: "મુખ્ય વાનગી",
    cat_fastfood: "ફાસ્ટ ફૂડ",
    cat_diet: "ડાયેટ અને હેલ્ધી",
    sub_tea: "ચા",
    sub_coffee: "કોફી",
    sub_cold: "ઠંડા પીણાં",
    sub_soft: "સોફ્ટ ડ્રિંક્સ",
    sub_smoothies: "સ્મૂધી",
    sub_mocktails: "મોકટેલ્સ",
    sub_laddus: "લાડુ",
    sub_halwa: "હલવો",
    sub_barfi: "બરફી",
    sub_syrup: "ચાસણી વાળી મીઠાઈ",
    sub_trad: "પરંપરાગત",
    sub_cakes: "કેક",
    sub_pastries: "પેસ્ટ્રી",
    sub_cookies: "કૂકીઝ",
    sub_pudding: "પુડિંગ",
    sub_icecream: "આઈસ્ક્રીમ",
    sub_curry: "શાક",
    sub_rice: "ભાત",
    sub_pasta: "પાસ્તા",
    sub_street: "સ્ટ્રીટ ફૂડ",
    sub_salad: "સલાડ",
    sub_burger: "બર્ગર અને સેન્ડવિચ",
    sub_pizza: "પિઝા",
    sub_chinese: "ચાઇનીઝ",
    sub_indian: "ભારતીય",
    sub_italian: "ઇટાલિયન",
    sub_mexican: "મેક્સિકન",
    sub_keto: "કીટો ડાયેટ",
    sub_vegan_special: "વેગન સ્પેશિયલ",
    sub_sandwiches: "સેન્ડવિચ",
    sub_chips: "ચિપ્સ અને ફ્રાઈસ",
    sub_high_protein: "હાઈ પ્રોટીન",
    sub_low_carb: "ઓછી કેલરી",
    curating: "શ્રેષ્ઠ વાનગીઓ શોધી રહ્યું છે...",
    no_recipes_book: "વાનગીઓ જોવા માટે શ્રેણી પસંદ કરો.",
    daily_nutrition: "દૈનિક પોષણ",
    total_intake: "કુલ લેવાયું",
    no_data: "ડેટા ઉપલબ્ધ નથી.",
    recipe_history: "રેસીપી ઇતિહાસ",
    favorites: "મનપસંદ",
    language: "ભાષા",
    units: "એકમો",
    diet_None: "કંઈ નહીં",
    diet_Vegetarian: "શાકાહારી",
    diet_Vegan: "વેગન",
    diet_Keto: "કીટો",
    diet_Paleo: "પેલેઓ",
    diet_Gluten_Free: "ગ્લુટેન મુક્ત",
    grocery_list: "કરિયાણાની યાદી",
    generate_to_see: "સામગ્રી જોવા માટે યોજના બનાવો.",
    items: "વસ્તુઓ",
    live_cooking: "લાઈવ રસોઈ",
    ing_reference: "સામગ્રી સંદર્ભ",
    confirm_reset: "શું તમે ખાતરી કરો છો? આ પૂર્વવત કરી શકાતું નથી.",
    confirm_delete_history: "ઇતિહાસ કાઢી નાખો?",
    copied: "રેસીપી કોપી કરી!",
    view_photos: "ફોટા જુઓ",
    generate_more: "વધુ બનાવો",
    photo_limit: "ફોટો લિમિટ પૂર્ણ",
    quota_exceeded: "દૈનિક મર્યાદા સમાપ્ત થઈ ગઈ છે.",
    personal_diet: "વ્યક્તિગત આહાર",
    age: "ઉંમર",
    gender: "લિંગ",
    weight: "વજન",
    height: "ઊંચાઈ",
    activity: "પ્રવૃત્તિ",
    goal: "લક્ષ્ય",
    target_calories: "લક્ષ્ય કેલરી"
  },
  pt: {
    ...enTranslations,
    cat_fastfood: "Fast Food",
    cat_diet: "Dieta e Saúde",
    sub_burger: "Hambúrgueres",
    sub_pizza: "Pizza",
    sub_chinese: "Chinês",
    sub_indian: "Indiano",
    sub_icecream: "Sorvete",
    sub_cold: "Bebidas Geladas",
    sub_sandwiches: "Sanduíches",
    sub_chips: "Batatas Fritas",
    sub_high_protein: "Alta Proteína",
    sub_low_carb: "Baixa Caloria",
    view_photos: "Ver Fotos",
    generate_more: "Gerar Mais",
    quota_exceeded: "Limite diário atingido.",
    personal_diet: "Dieta Pessoal",
    age: "Idade",
    gender: "Gênero",
    weight: "Peso",
    height: "Altura",
    activity: "Atividade",
    goal: "Meta",
    male: "Masculino",
    female: "Feminino",
    lose_weight: "Perder Peso",
    maintain: "Manter",
    build_muscle: "Ganhar Músculo",
    target_calories: "Calorias Alvo",
    daily_goal: "Meta Diária"
  },
  hi: {
    ...enTranslations,
    cat_fastfood: "फास्ट फूड",
    cat_diet: "डाइट और हेल्दी",
    sub_burger: "बर्गर और सैंडविच",
    sub_pizza: "पिज़्ज़ा",
    sub_chinese: "चाइनीज",
    sub_indian: "भारतीय",
    sub_icecream: "आइसक्रीम",
    sub_cold: "कोल्ड ड्रिंक्स",
    sub_sandwiches: "सैंडविच",
    sub_chips: "चिप्स और फ्राइज",
    sub_high_protein: "हाई प्रोटीन",
    sub_low_carb: "कम कैलोरी",
    view_photos: "फोटो देखें",
    generate_more: "और बनाएं",
    quota_exceeded: "दैनिक सीमा समाप्त हो गई है।",
    personal_diet: "व्यक्तिगत आहार",
    age: "आयु",
    gender: "लिंग",
    weight: "वजन",
    height: "ऊंचाई",
    activity: "गतिविधि",
    goal: "लक्ष्य",
    target_calories: "लक्ष्य कैलोरी"
  },
  zh: {
    ...enTranslations,
    cat_fastfood: "快餐",
    cat_diet: "健康饮食",
    sub_burger: "汉堡",
    sub_pizza: "披萨",
    sub_chinese: "中餐",
    sub_indian: "印度菜",
    sub_icecream: "冰淇淋",
    sub_cold: "冷饮",
    sub_sandwiches: "三明治",
    sub_chips: "薯条",
    sub_high_protein: "高蛋白",
    sub_low_carb: "低卡路里",
    view_photos: "查看照片",
    generate_more: "生成更多",
    quota_exceeded: "达到每日限额。",
    personal_diet: "个人饮食",
    age: "年龄",
    gender: "性别",
    weight: "体重",
    height: "身高",
    activity: "活动量",
    goal: "目标",
    target_calories: "目标卡路里"
  },
  ar: {
    ...enTranslations,
    cat_fastfood: "وجبات سريعة",
    cat_diet: "صحي وحمية",
    sub_burger: "برجر",
    sub_pizza: "بيتزا",
    sub_chinese: "صيني",
    sub_indian: "هندي",
    sub_icecream: "آيس كريم",
    sub_cold: "مشروبات باردة",
    sub_sandwiches: "ساندويتش",
    sub_chips: "شيبس",
    sub_high_protein: "بروتين عالي",
    sub_low_carb: "سعرات قليلة",
    view_photos: "عرض الصور",
    generate_more: "توليد المزيد",
    quota_exceeded: "تم الوصول إلى الحد اليومي.",
    personal_diet: "نظام غذائي شخصي",
    age: "العمر",
    gender: "الجنس",
    weight: "الوزن",
    height: "الطول",
    activity: "النشاط",
    goal: "الهدف",
    target_calories: "السعرات المستهدفة"
  },
  ru: {
    ...enTranslations,
    cat_fastfood: "Фастфуд",
    cat_diet: "Диетическое",
    sub_burger: "Бургеры",
    sub_pizza: "Пицца",
    sub_chinese: "Китайская",
    sub_indian: "Индийская",
    sub_icecream: "Мороженое",
    sub_cold: "Холодные напитки",
    sub_sandwiches: "Сэндвичи",
    sub_chips: "Чипсы",
    sub_high_protein: "Высокий белок",
    sub_low_carb: "Низкокалорийное",
    view_photos: "Смотреть фото",
    generate_more: "Ещё фото",
    quota_exceeded: "Дневной лимит исчерпан.",
    personal_diet: "Персональная диета",
    age: "Возраст",
    gender: "Пол",
    weight: "Вес",
    height: "Рост",
    activity: "Активность",
    goal: "Цель",
    target_calories: "Цель калорий"
  },
  ja: {
    ...enTranslations,
    cat_fastfood: "ファストフード",
    cat_diet: "ダイエット・健康",
    sub_burger: "バーガー",
    sub_pizza: "ピザ",
    sub_chinese: "中華",
    sub_indian: "インド料理",
    sub_icecream: "アイスクリーム",
    sub_cold: "冷たい飲み物",
    sub_sandwiches: "サンドイッチ",
    sub_chips: "ポテト",
    sub_high_protein: "高タンパク",
    sub_low_carb: "低カロリー",
    view_photos: "写真を見る",
    generate_more: "もっと生成",
    quota_exceeded: "1日の制限に達しました。",
    personal_diet: "パーソナルダイエット",
    age: "年齢",
    gender: "性別",
    weight: "体重",
    height: "身長",
    activity: "活動レベル",
    goal: "目標",
    target_calories: "目標カロリー"
  },
  it: { ...enTranslations, plan: "Piano", shop: "Spesa", stats: "Stat.", profile: "Profilo", book: "Libro", generate: "Genera", start: "Inizia", back: "Indietro", personal_diet: "Dieta Personale" },
  ko: { ...enTranslations, plan: "계획", shop: "쇼핑", stats: "통계", profile: "프로필", book: "요리책", generate: "생성", start: "시작", back: "뒤로", personal_diet: "개인 식단" },
  tr: { ...enTranslations, plan: "Plan", shop: "Alışveriş", stats: "İstat.", profile: "Profil", book: "Kitap", generate: "Oluştur", start: "Başla", back: "Geri", personal_diet: "Kişisel Diyet" },
  vi: { ...enTranslations, plan: "Kế hoạch", shop: "Mua sắm", stats: "Thống kê", profile: "Hồ sơ", book: "Sách", generate: "Tạo", start: "Bắt đầu", back: "Quay lại", personal_diet: "Chế độ ăn cá nhân" },
  nl: { ...enTranslations, plan: "Plan", shop: "Winkel", stats: "Stats", profile: "Profiel", book: "Boek", generate: "Genereren", start: "Starten", back: "Terug", personal_diet: "Persoonlijk dieet" },
  id: { ...enTranslations, plan: "Rencana", shop: "Belanja", stats: "Statistik", profile: "Profil", book: "Buku", generate: "Buat", start: "Mulai", back: "Kembali", personal_diet: "Diet Pribadi" },
  th: { ...enTranslations, plan: "แผน", shop: "ซื้อของ", stats: "สถิติ", profile: "โปรไฟล์", book: "หนังสือ", generate: "สร้าง", start: "เริ่ม", back: "กลับ", personal_diet: "อาหารส่วนบุคคล" },
  bn: { ...enTranslations, plan: "পরিকল্পনা", shop: "কেনাকাটা", stats: "পরিসংখ্যান", profile: "প্রোফাইল", book: "বई" },
  pa: { ...enTranslations, plan: "ਯੋਜਨਾ", shop: "ਖਰੀਦਦਾਰੀ", stats: "ਅੰਕੜੇ", profile: "ਪ੍ਰੋਫਾਈਲ", book: "ਕਿਤਾਬ" },
};

export const COMMON_INGREDIENTS = [
  "Chicken", "Beef", "Pork", "Salmon", "Tuna", "Shrimp", "Eggs", "Milk", "Cheese", "Butter", "Cream", "Yogurt",
  "Rice", "Pasta", "Bread", "Flour", "Sugar", "Salt", "Pepper", "Garlic", "Onion", "Tomato", "Potato", "Carrot",
  "Broccoli", "Spinach", "Kale", "Lettuce", "Cucumber", "Avocado", "Lemon", "Lime", "Apple", "Banana", "Orange",
  "Strawberry", "Blueberry", "Raspberry", "Olive Oil", "Vegetable Oil", "Soy Sauce", "Vinegar", "Honey", "Mustard",
  "Mayonnaise", "Ketchup", "Coffee", "Tea", "Chocolate", "Vanilla", "Cinnamon", "Ginger", "Basil", "Oregano",
  "Parsley", "Cilantro", "Thyme", "Rosemary", "Cumin", "Paprika", "Turmeric", "Chili Powder", "Beans", "Lentils",
  "Chickpeas", "Quinoa", "Oats", "Nuts", "Almonds", "Walnuts", "Peanuts", "Cashews", "Mushrooms", "Zucchini",
  "Eggplant", "Bell Pepper", "Corn", "Peas", "Asparagus", "Cauliflower", "Cabbage", "Celery", "Scallions", "Leek",
  "Bacon", "Sausage", "Ham", "Turkey", "Duck", "Lamb", "Cod", "Tilapia", "Tofu", "Tempeh", "Seitan", "Coconut Milk",
  "Almond Milk", "Soy Milk", "Oat Milk", "Maple Syrup", "Agave", "Stevia", "Baking Powder", "Baking Soda", "Yeast",
  "Cornstarch", "Cocoa Powder", "Chocolate Chips", "Raisins", "Cranberries", "Dates", "Figs", "Apricots", "Peaches",
  "Pears", "Grapes", "Melon", "Watermelon", "Pineapple", "Mango", "Papaya", "Kiwi", "Pomegranate", "Cherries",
  "Plums", "Nectarines", "Grapefruit", "Mandarin", "Cantaloupe", "Honeydew", "Blackberries", "Boysenberries",
  "Currants", "Gooseberries", "Elderberries", "Mulberries", "Quince", "Persimmon", "Guava", "Passion Fruit",
  "Lychee", "Dragon Fruit", "Star Fruit", "Durian", "Jackfruit", "Breadfruit", "Plantain", "Cassava", "Taro",
  "Yam", "Sweet Potato", "Beet", "Radish", "Turnip", "Parsnip", "Rutabaga", "Jicama", "Watercress", "Arugula",
  "Endive", "Radicchio", "Fennel", "Artichoke", "Okra", "Bamboo Shoots", "Water Chestnuts", "Bean Sprouts",
  "Alfalfa Sprouts", "Seaweed", "Nori", "Kombu", "Wakame", "Dulse", "Agar", "Gelatin", "Pectin", "Rennet"
];